export const MOCK_USERS: Record<string, any> = {
    'luis-rojas': {
        id: 'luis-rojas',
        username: 'Luis Rojas',
        name: 'Luis Rojas',
        profession: 'Tatuador especialista en Realismo y Color',
        bio: 'Especialista en tatuajes realistas a color.\n10 años de experiencia.\nDisponible para citas.',
        avatar: '',
        location: 'Cali, Colombia',
        followersCount: 312,
        followingCount: 89,
        instagram: 'instagram.com/luisrojas.ink',
        behance: 'behance.net/luisrojas',
        website: '',
    },
    'diana-cruz': {
        id: 'diana-cruz',
        username: 'Diana Cruz',
        name: 'Diana Cruz',
        profession: 'Tatuadora Fine Line y Minimalista',
        bio: 'Fine line y blackwork minimalista.\nCali, Colombia.\nDM para agendas.',
        avatar: '',
        location: 'Cali, Colombia',
        followersCount: 398,
        followingCount: 145,
        instagram: 'instagram.com/dianacruz.tattoo',
        behance: 'behance.net/dianacruz',
        website: '',
    },
    'pablo-gil': {
        id: 'pablo-gil',
        username: 'Pablo Gil',
        name: 'Pablo Gil',
        profession: 'Tatuador Tribal y Geométrico',
        bio: 'Especialista en tribal y geométrico.\nTatuador profesional desde 2015.\nRadicado en Bogotá.',
        avatar: '',
        location: 'Bogotá, Colombia',
        followersCount: 423,
        followingCount: 67,
        instagram: 'instagram.com/pablogil.tattoo',
        behance: '',
        website: '',
    },
    'sofia-toro': {
        id: 'sofia-toro',
        username: 'Sofía Toro',
        name: 'Sofía Toro',
        profession: 'Lettering y Caligrafía',
        bio: 'Especialista en lettering y caligrafía.\nCada trazo cuenta una historia.\nDisponible para proyectos personalizados.',
        avatar: '',
        location: 'Medellín, Colombia',
        followersCount: 189,
        followingCount: 42,
        instagram: 'instagram.com/sofiatoro.ink',
        behance: 'behance.net/sofiatoro',
        website: 'sofiatoro.com',
    },
};

export const MOCK_STUDIOS: Record<string, any> = {
    'ink-master': {
        id: 'ink-master',
        name: 'Ink Master Studio',
        description: 'Estudio profesional de tatuajes.\nEspecialistas en Neo Tradicional.\n5 años de experiencia en la industria.',
        logoUrl: '',
        location: 'Bogotá, Colombia',
        rating: 4.9,
        followersCount: 234,
        website: '',
    },
    'black-ink': {
        id: 'black-ink',
        name: 'Black Ink Studio',
        description: 'Estudio especializado en Blackwork y Realismo.\nTécnicas modernas y tradicionales.\nAmbiente profesional y acogedor.',
        logoUrl: '',
        location: 'Bogotá, Colombia',
        rating: 4.9,
        followersCount: 567,
        website: '',
    },
    'ink-starter-studio': {
        id: 'ink-starter-studio',
        name: 'Ink Starter Studio',
        description: 'Estudio de tatuajes para iniciados y expertos.\nPrecios accesibles.\nExcelente atención.',
        logoUrl: '/images/logos/ink-starter-studio.png',
        location: 'Cali, Colombia',
        rating: 4.5,
        followersCount: 23,
        website: '',
    },
    'mini-tattoo-cali': {
        id: 'mini-tattoo-cali',
        name: 'Mini Tattoo Cali',
        description: 'Especialistas en mini tatuajes.\nDiseños pequeños con gran detalle.\nPerfecto para tu primer tatuaje.',
        logoUrl: '/images/logos/mini-tattoo-cali.png',
        location: 'San Fernando, Cali',
        rating: 4.3,
        followersCount: 15,
        website: '',
    },
    'fine-line-studio': {
        id: 'fine-line-studio',
        name: 'Fine Line Studio',
        description: 'Estudio especializado en Fine Line.\nDiseños minimalistas y elegantes.\nArte que habla por sí solo.',
        logoUrl: '/images/logos/fine-line-studio.png',
        location: 'Granada, Cali',
        rating: 4.8,
        followersCount: 42,
        website: '',
    },
    'neo-art-studio': {
        id: 'neo-art-studio',
        name: 'Neo Art Studio',
        description: 'Estudio de arte Neo Tradicional.\nColor, detalle y creatividad.\nTransformamos tus ideas en arte.',
        logoUrl: '/images/logos/neo-art-studio.png',
        location: 'San Antonio, Cali',
        rating: 4.9,
        followersCount: 31,
        website: '',
    },
    'real-ink-tattoo': {
        id: 'real-ink-tattoo',
        name: 'Real Ink Tattoo',
        description: 'Realismo y Color.\nTatuajes hiperrealistas.\nArte que cobra vida.',
        logoUrl: '/images/logos/real-ink-tattoo.png',
        location: 'Centro, Cali',
        rating: 4.7,
        followersCount: 56,
        website: '',
    },
    'black-house-tattoo': {
        id: 'black-house-tattoo',
        name: 'Black House Tattoo',
        description: 'Blackwork y Diseño.\nEstilo oscuro y sofisticado.\nEspecialistas en piezas grandes.',
        logoUrl: '/images/logos/black-house-tattoo.png',
        location: 'Granada, Cali',
        rating: 4.9,
        followersCount: 78,
        website: '',
    },
    'black-ink-studio': {
        id: 'black-ink-studio',
        name: 'Black Ink Studio',
        description: 'Blackwork y Realismo.\nTécnicas modernas.\n10 años de experiencia.',
        logoUrl: '',
        location: 'Bogotá, Colombia',
        rating: 4.9,
        followersCount: 234,
        website: '',
    },
    'estudio-79-tattoo': {
        id: 'estudio-79-tattoo',
        name: 'Estudio 79 Tattoo',
        description: 'Estudio de tatuajes con más de 15 años de trayectoria.\nExpertos en todos los estilos.',
        logoUrl: '',
        location: 'Bogotá, Colombia',
        rating: 4.9,
        followersCount: 456,
        website: '',
    },
    'la-vida-tattoo': {
        id: 'la-vida-tattoo',
        name: 'La Vida Tattoo',
        description: 'Arte y vida en cada trazo.\nEstudio boutique en Medellín.\nEspecialistas en color.',
        logoUrl: '',
        location: 'Medellín, Colombia',
        rating: 4.8,
        followersCount: 312,
        website: '',
    },
    'tinta-finita': {
        id: 'tinta-finita',
        name: 'Tinta Finita',
        description: 'Fine Line y Minimalismo.\nDiseños sutiles y elegantes.\nCali, Colombia.',
        logoUrl: '',
        location: 'Cali, Colombia',
        rating: 4.7,
        followersCount: 189,
        website: '',
    },
    'seven-ink-studio': {
        id: 'seven-ink-studio',
        name: 'Seven Ink Studio',
        description: 'Estudio moderno con 7 artistas.\nTodos los estilos.\nCartagena, Colombia.',
        logoUrl: '',
        location: 'Cartagena, Colombia',
        rating: 4.9,
        followersCount: 234,
        website: '',
    },
};

export const MOCK_USER_POSTS: Record<string, any[]> = {
    'luis-rojas': [
        { id: 'mock-lr-1', title: 'Color realismo ave exótica', content: 'Trabajo de realismo a color en antebrazo. Ave exótica con detalles en plumaje.', imageUrl: '/images/tattoos/tattoo-7.jpg', likesCount: 312, commentsCount: 78, createdAt: '2025-12-15T10:00:00Z' },
        { id: 'mock-lr-2', title: 'Leopardo realismo', content: 'Realismo en blanco y negro de leopardo.', imageUrl: '', likesCount: 145, commentsCount: 23, createdAt: '2025-11-20T10:00:00Z' },
        { id: 'mock-lr-3', title: 'Rostro hiperrealista', content: 'Retrato hiperrealista en escala de grises.', imageUrl: '', likesCount: 89, commentsCount: 12, createdAt: '2025-10-10T10:00:00Z' },
    ],
    'diana-cruz': [
        { id: 'mock-dc-1', title: 'Fine line rostro femenino', content: 'Fine line de rostro femenino en antebrazo. Líneas sutiles y elegantes.', imageUrl: '/images/tattoos/tattoo-10.jpg', likesCount: 398, commentsCount: 67, createdAt: '2026-01-10T10:00:00Z' },
        { id: 'mock-dc-2', title: 'Corazón anatómico', content: 'Fine line de corazón anatómico con detalles botánicos.', imageUrl: '', likesCount: 234, commentsCount: 45, createdAt: '2025-12-01T10:00:00Z' },
    ],
    'pablo-gil': [
        { id: 'mock-pg-1', title: 'Tribal brazo geométrico', content: 'Manga tribal con diseño geométrico moderno. Líneas precisas y sombreado.', imageUrl: '/images/tattoos/tattoo-9.jpg', likesCount: 423, commentsCount: 89, createdAt: '2026-02-05T10:00:00Z' },
        { id: 'mock-pg-2', title: 'Maya geométrico', content: 'Diseño maya con patrones geométricos contemporáneos.', imageUrl: '', likesCount: 167, commentsCount: 34, createdAt: '2026-01-15T10:00:00Z' },
    ],
    'sofia-toro': [
        { id: 'mock-st-1', title: 'Lettering frase completa en espalda', content: 'Frase completa en lettering cursivo en la espalda. Caligrafía personalizada.', imageUrl: '/images/tattoos/tattoo-6.jpg', likesCount: 189, commentsCount: 42, createdAt: '2025-11-25T10:00:00Z' },
        { id: 'mock-st-2', title: 'Nombre en script', content: 'Lettering script para nombre en antebrazo.', imageUrl: '', likesCount: 78, commentsCount: 15, createdAt: '2025-10-30T10:00:00Z' },
    ],
};

export const MOCK_STUDIO_POSTS: Record<string, any[]> = {
    'ink-master': [
        { id: 'mock-im-1', title: 'Neo tradicional rosa y dagas', content: 'Neo tradicional con rosa, dagas y detalles ornamentales.', imageUrl: '/images/tattoos/tattoo-5.jpg', likesCount: 234, commentsCount: 56, createdAt: '2025-12-20T10:00:00Z' },
    ],
    'black-ink': [
        { id: 'mock-bi-1', title: 'Anime sleeve completo', content: 'Manga completa de anime. Personajes y escenas detalladas.', imageUrl: '/images/tattoos/tattoo-8.jpg', likesCount: 567, commentsCount: 102, createdAt: '2026-01-20T10:00:00Z' },
    ],
};

export function getMockPostsForUser(userId: string): any[] {
    return MOCK_USER_POSTS[userId] || [];
}

export const MOCK_FEED_POSTS = [
    {
        id: 'mock-feed-1', title: 'Neo tradicional rosa y dagas', content: 'Neo tradicional con rosa, dagas y detalles ornamentales. Trabajo realizado en Ink Master Studio.',
        imageUrl: '/images/tattoos/tattoo-5.jpg', likesCount: 234, commentsCount: 56,
        user: { id: 'ink-master', username: 'Ink Master', avatar: '' },
        category: { name: 'Neo Tradicional' }, location: 'Bogotá, Colombia',
        createdAt: '2025-12-20T10:00:00Z', likedByCurrentUser: false,
    },
    {
        id: 'mock-feed-2', title: 'Lettering frase completa en espalda', content: 'Frase completa en lettering cursivo en la espalda. Caligrafía personalizada para cada cliente.',
        imageUrl: '/images/tattoos/tattoo-6.jpg', likesCount: 189, commentsCount: 42,
        user: { id: 'sofia-toro', username: 'Sofía Toro', avatar: '' },
        category: { name: 'Lettering' }, location: 'Medellín, Colombia',
        createdAt: '2025-11-25T10:00:00Z', likedByCurrentUser: false,
    },
    {
        id: 'mock-feed-3', title: 'Color realismo ave exótica', content: 'Trabajo de realismo a color en antebrazo. Ave exótica con detalles en plumaje.',
        imageUrl: '/images/tattoos/tattoo-7.jpg', likesCount: 312, commentsCount: 78,
        user: { id: 'luis-rojas', username: 'Luis Rojas', avatar: '' },
        category: { name: 'Realismo' }, location: 'Cali, Colombia',
        createdAt: '2025-12-15T10:00:00Z', likedByCurrentUser: false,
    },
    {
        id: 'mock-feed-4', title: 'Anime sleeve completo', content: 'Manga completa de anime. Personajes y escenas detalladas en estilo japonés.',
        imageUrl: '/images/tattoos/tattoo-8.jpg', likesCount: 567, commentsCount: 102,
        user: { id: 'black-ink', username: 'Black Ink', avatar: '' },
        category: { name: 'Anime' }, location: 'Bogotá, Colombia',
        createdAt: '2026-01-20T10:00:00Z', likedByCurrentUser: false,
    },
    {
        id: 'mock-feed-5', title: 'Tribal brazo geométrico', content: 'Manga tribal con diseño geométrico moderno. Líneas precisas y sombreado impecable.',
        imageUrl: '/images/tattoos/tattoo-9.jpg', likesCount: 423, commentsCount: 89,
        user: { id: 'pablo-gil', username: 'Pablo Gil', avatar: '' },
        category: { name: 'Tribal' }, location: 'Bogotá, Colombia',
        createdAt: '2026-02-05T10:00:00Z', likedByCurrentUser: false,
    },
    {
        id: 'mock-feed-6', title: 'Fine line rostro femenino', content: 'Fine line de rostro femenino en antebrazo. Líneas sutiles y elegantes.',
        imageUrl: '/images/tattoos/tattoo-10.jpg', likesCount: 398, commentsCount: 67,
        user: { id: 'diana-cruz', username: 'Diana Cruz', avatar: '' },
        category: { name: 'Fine Line' }, location: 'Cali, Colombia',
        createdAt: '2026-01-10T10:00:00Z', likedByCurrentUser: false,
    },
];

export function getMockPostsForStudio(studioId: string): any[] {
    if (MOCK_STUDIO_POSTS[studioId]) return MOCK_STUDIO_POSTS[studioId];
    return [
        { id: `mock-${studioId}-1`, title: 'Trabajo destacado', content: 'Trabajo realizado en nuestro estudio.', imageUrl: '', likesCount: 0, commentsCount: 0, createdAt: new Date().toISOString() },
    ];
}