export const MOCK_USERS: Record<string, any> = {
    'luis-rojas': {
        id: 'luis-rojas',
        username: 'Luis Rojas',
        name: 'Luis Rojas',
        profession: 'Especialista en Realismo y Color',
        bio: 'Especialista en tatuajes realistas a color.\n10 años de experiencia.\nDisponible para citas.',
        avatar: '',
        location: 'Cali, Colombia',
        followersCount: 312,
        followingCount: 89,
        instagram: 'instagram.com/luisrojas.ink',
        behance: 'behance.net/luisrojas',
        website: '',
    },
    'diana-cruz': {
        id: 'diana-cruz',
        username: 'Diana Cruz',
        name: 'Diana Cruz',
        profession: 'Tatuadora Fine Line y Minimalista',
        bio: 'Fine line y blackwork minimalista.\nCali, Colombia.\nDM para agendas.',
        avatar: '',
        location: 'Cali, Colombia',
        followersCount: 398,
        followingCount: 145,
        instagram: 'instagram.com/dianacruz.tattoo',
        behance: 'behance.net/dianacruz',
        website: '',
    },
    'pablo-gil': {
        id: 'pablo-gil',
        username: 'Pablo Gil',
        name: 'Pablo Gil',
        profession: 'Tatuador Tribal y Geométrico',
        bio: 'Especialista en tribal y geométrico.\nTatuador profesional desde 2015.\nRadicado en Bogotá.',
        avatar: '',
        location: 'Bogotá, Colombia',
        followersCount: 423,
        followingCount: 67,
        instagram: 'instagram.com/pablogil.tattoo',
        behance: '',
        website: '',
    },
    'camilasanchez': {
        id: 'camilasanchez',
        username: 'Camila Sánchez',
        name: 'Camila Sánchez',
        profession: 'Especialista en Lettering y Caligrafía',
        bio: 'Especialista en Lettering y Caligrafía.\nCada trazo cuenta una historia.\nDiseños personalizados para proyectos únicos.\nDisponible para trabajos por encargo.',
        avatar: '',
        location: 'Medellín, Colombia',
        followersCount: 189,
        followingCount: 42,
        instagram: 'instagram.com/camilasanchez.ink',
        behance: 'behance.net/camilasanchez',
        website: '',
    },
};

export const MOCK_STUDIOS: Record<string, any> = {
    'ink-master': {
        id: 'ink-master',
        name: 'Ink Master Studio',
        description: 'Estudio profesional de tatuajes.\nEspecialistas en Neo Tradicional.\n5 años de experiencia en la industria.',
        specialties: 'Neo Tradicional, Blackwork, Color',
        logoUrl: '/images/logos/master-ink-collective.png',
        location: 'Bogotá, Colombia',
        rating: 4.9,
        followersCount: 234,
        website: '',
        instagram: 'instagram.com/inkmaster.bogota',
        behance: 'behance.net/inkmaster',
    },
    'black-ink': {
        id: 'black-ink',
        name: 'Black Ink Studio',
        description: 'Estudio especializado en Blackwork y Realismo.\nTécnicas modernas y tradicionales.\nAmbiente profesional y acogedor.',
        specialties: 'Blackwork, Realismo, Anime',
        logoUrl: '/images/logos/blackwork-studio.png',
        location: 'Bogotá, Colombia',
        rating: 4.9,
        followersCount: 567,
        website: '',
        instagram: 'instagram.com/blackink.bogota',
        behance: 'behance.net/blackink',
    },
    'ink-starter-studio': {
        id: 'ink-starter-studio',
        name: 'Ink Starter Studio',
        description: 'Estudio de tatuajes para iniciados y expertos.\nPrecios accesibles.\nExcelente atención.',
        specialties: 'Blackwork, Fine Line, Minimalista',
        logoUrl: '/images/logos/ink-starter-studio.png',
        location: 'Cali, Colombia',
        rating: 4.5,
        followersCount: 23,
        website: '',
        instagram: 'instagram.com/inkstarter.cali',
        behance: 'behance.net/inkstarter',
    },
    'mini-tattoo-cali': {
        id: 'mini-tattoo-cali',
        name: 'Mini Tattoo Cali',
        description: 'Especialistas en mini tatuajes.\nDiseños pequeños con gran detalle.\nPerfecto para tu primer tatuaje.',
        specialties: 'Mini tatuajes, Fine Line, Minimalista',
        logoUrl: '/images/logos/mini-tattoo-cali.png',
        location: 'San Fernando, Cali',
        rating: 4.3,
        followersCount: 15,
        website: '',
        instagram: 'instagram.com/minitattoo.cali',
        behance: 'behance.net/minitattoo',
    },
    'fine-line-studio': {
        id: 'fine-line-studio',
        name: 'Fine Line Studio',
        description: 'Estudio especializado en Fine Line.\nDiseños minimalistas y elegantes.\nArte que habla por sí solo.',
        specialties: 'Fine Line, Minimalista, Blackwork',
        logoUrl: '/images/logos/fine-line-studio.png',
        location: 'Granada, Cali',
        rating: 4.8,
        followersCount: 42,
        website: '',
        instagram: 'instagram.com/fineline.cali',
        behance: 'behance.net/finelinestudio',
    },
    'neo-art-studio': {
        id: 'neo-art-studio',
        name: 'Neo Art Studio',
        description: 'Estudio de arte Neo Tradicional.\nColor, detalle y creatividad.\nTransformamos tus ideas en arte.',
        specialties: 'Neo Tradicional, Color, Lettering',
        logoUrl: '/images/logos/neo-art-studio.png',
        location: 'San Antonio, Cali',
        rating: 4.9,
        followersCount: 31,
        website: '',
        instagram: 'instagram.com/neoart.cali',
        behance: 'behance.net/neoartstudio',
    },
    'real-ink-tattoo': {
        id: 'real-ink-tattoo',
        name: 'Real Ink Tattoo',
        description: 'Realismo y Color.\nTatuajes hiperrealistas.\nArte que cobra vida.',
        specialties: 'Realismo, Color, Retratos',
        logoUrl: '/images/logos/real-ink-tattoo.png',
        location: 'Centro, Cali',
        rating: 4.7,
        followersCount: 56,
        website: '',
        instagram: 'instagram.com/realink.cali',
        behance: 'behance.net/realinktattoo',
    },
    'black-house-tattoo': {
        id: 'black-house-tattoo',
        name: 'Black House Tattoo',
        description: 'Blackwork y Diseño.\nEstilo oscuro y sofisticado.\nEspecialistas en piezas grandes.',
        specialties: 'Blackwork, Tribal, Geométrico',
        logoUrl: '/images/logos/black-house-tattoo.png',
        location: 'Granada, Cali',
        rating: 4.9,
        followersCount: 78,
        website: '',
        instagram: 'instagram.com/blackhouse.cali',
        behance: 'behance.net/blackhouse',
    },
    'black-ink-studio': {
        id: 'black-ink-studio',
        name: 'Black Ink Studio',
        description: 'Blackwork y Realismo.\nTécnicas modernas.\n10 años de experiencia.',
        specialties: 'Blackwork, Realismo, Geométrico',
        logoUrl: '/images/logos/blackwork-studio.png',
        location: 'Bogotá, Colombia',
        rating: 4.9,
        followersCount: 234,
        website: '',
        instagram: 'instagram.com/blackinkstudio.bogota',
        behance: 'behance.net/blackinkstudio',
    },
    'estudio-79-tattoo': {
        id: 'estudio-79-tattoo',
        name: 'Estudio 79 Tattoo',
        description: 'Estudio de tatuajes con más de 15 años de trayectoria.\nExpertos en todos los estilos.',
        specialties: 'Tradicional, Neo Tradicional, Color',
        logoUrl: '/images/logos/blackwork-studio.png',
        location: 'Bogotá, Colombia',
        rating: 4.9,
        followersCount: 456,
        website: '',
        instagram: 'instagram.com/estudio79.bogota',
        behance: 'behance.net/estudio79',
    },
    'la-vida-tattoo': {
        id: 'la-vida-tattoo',
        name: 'La Vida Tattoo',
        description: 'Arte y vida en cada trazo.\nEstudio boutique en Medellín.\nEspecialistas en color.',
        specialties: 'Color, Realismo, Fine Line',
        logoUrl: '',
        location: 'Medellín, Colombia',
        rating: 4.8,
        followersCount: 312,
        website: '',
        instagram: 'instagram.com/lavidatattoo.medellin',
        behance: 'behance.net/lavidatattoo',
    },
    'tinta-finita': {
        id: 'tinta-finita',
        name: 'Tinta Finita',
        description: 'Fine Line y Minimalismo.\nDiseños sutiles y elegantes.\nCali, Colombia.',
        specialties: 'Fine Line, Minimalista, Lettering',
        logoUrl: '/images/logos/fine-line-studio.png',
        location: 'Cali, Colombia',
        rating: 4.7,
        followersCount: 189,
        website: '',
        instagram: 'instagram.com/tintafinita.cali',
        behance: 'behance.net/tintafinita',
    },
    'seven-ink-studio': {
        id: 'seven-ink-studio',
        name: 'Seven Ink Studio',
        description: 'Estudio moderno con 7 artistas.\nTodos los estilos.\nCartagena, Colombia.',
        specialties: 'Blackwork, Realismo, Tradicional, Fine Line',
        logoUrl: '',
        location: 'Cartagena, Colombia',
        rating: 4.9,
        followersCount: 234,
        website: '',
        instagram: 'instagram.com/sevenink.cartagena',
        behance: 'behance.net/sevenink',
    },
};

export const MOCK_USER_POSTS: Record<string, any[]> = {
    'luis-rojas': [
        { id: 'mock-lr-1', title: 'Ave Fénix', content: 'Trabajo de realismo a color en antebrazo. Ave Fénix con detalles en plumaje.', imageUrl: '/images/tattoos/tattoo-7.jpg', likesCount: 312, commentsCount: 78, createdAt: '2025-12-15T10:00:00Z' },
        { id: 'mock-lr-2', title: 'Leopardo realista', content: 'Realismo en blanco y negro de leopardo.', imageUrl: '/images/tattoos/tattoo-1.jpg', likesCount: 145, commentsCount: 23, createdAt: '2025-11-20T10:00:00Z' },
        { id: 'mock-lr-3', title: 'Rostro hiperrealista', content: 'Retrato hiperrealista en escala de grises.', imageUrl: '/images/tattoos/tattoo-2.jpg', likesCount: 89, commentsCount: 12, createdAt: '2025-10-10T10:00:00Z' },
    ],
    'diana-cruz': [
        { id: 'mock-dc-1', title: 'Fine line rostro femenino', content: 'Fine line de rostro femenino en antebrazo. Líneas sutiles y elegantes.', imageUrl: '/images/tattoos/tattoo-10.jpg', likesCount: 398, commentsCount: 67, createdAt: '2026-01-10T10:00:00Z' },
        { id: 'mock-dc-2', title: 'Corazón anatómico', content: 'Fine line de corazón anatómico con detalles botánicos.', imageUrl: '/images/tattoos/tattoo-4.jpg', likesCount: 234, commentsCount: 45, createdAt: '2025-12-01T10:00:00Z' },
    ],
    'pablo-gil': [
        { id: 'mock-pg-1', title: 'Tribal brazo geométrico', content: 'Manga tribal con diseño geométrico moderno. Líneas precisas y sombreado.', imageUrl: '/images/tattoos/tattoo-9.jpg', likesCount: 423, commentsCount: 89, createdAt: '2026-02-05T10:00:00Z' },
        { id: 'mock-pg-2', title: 'Maya geométrico', content: 'Diseño maya con patrones geométricos contemporáneos.', imageUrl: '/images/tattoos/tattoo-3.jpg', likesCount: 167, commentsCount: 34, createdAt: '2026-01-15T10:00:00Z' },
    ],
    'camilasanchez': [
        { id: 'mock-cs-1', title: 'Lettering frase completa en espalda', content: 'Frase completa en lettering cursivo en la espalda. Caligrafía personalizada.', imageUrl: '/images/tattoos/tattoo-6.jpg', likesCount: 189, commentsCount: 42, createdAt: '2025-11-25T10:00:00Z' },
        { id: 'mock-cs-2', title: 'Astronauta minimalista', content: 'Astronauta minimalista en estilo fine line. Diseño sutil y elegante.', imageUrl: '/images/tattoos/tattoo-3.jpg', likesCount: 78, commentsCount: 15, createdAt: '2025-10-30T10:00:00Z' },
    ],
};

export const MOCK_STUDIO_POSTS: Record<string, any[]> = {
    'ink-master': [
        { id: 'mock-im-1', title: 'Neo tradicional rosa y dagas', content: 'Neo tradicional con rosa, dagas y detalles ornamentales.', imageUrl: '/images/tattoos/tattoo-5.jpg', likesCount: 234, commentsCount: 56, createdAt: '2025-12-20T10:00:00Z' },
        { id: 'mock-im-2', title: 'Neo tradicional reloj y brújula', content: 'Diseño neo tradicional de reloj con brújula y rosas.', imageUrl: '/images/tattoos/tattoo-2.jpg', likesCount: 189, commentsCount: 34, createdAt: '2026-01-15T10:00:00Z' },
        { id: 'mock-im-3', title: 'Rosa negra neo tradicional', content: 'Rosa negra con hojas ornamentales en estilo neo tradicional.', imageUrl: '/images/tattoos/tattoo-1.jpg', likesCount: 312, commentsCount: 67, createdAt: '2026-02-01T10:00:00Z' },
    ],
    'black-ink': [
        { id: 'mock-bi-1', title: 'Anime sleeve completo', content: 'Manga completa de anime. Personajes y escenas detalladas.', imageUrl: '/images/tattoos/tattoo-8.jpg', likesCount: 567, commentsCount: 102, createdAt: '2026-01-20T10:00:00Z' },
    ],
    'black-ink-studio': [
        { id: 'mock-bis-1', title: 'Manga blackwork brazo', content: 'Manga completa en blackwork con diseños geométricos.', imageUrl: '/images/tattoos/tattoo-9.jpg', likesCount: 234, commentsCount: 45, createdAt: '2025-12-10T10:00:00Z' },
        { id: 'mock-bis-2', title: 'Realismo lobo', content: 'Lobo hiperrealista en escala de grises.', imageUrl: '/images/tattoos/tattoo-2.jpg', likesCount: 178, commentsCount: 32, createdAt: '2026-01-05T10:00:00Z' },
    ],
    'fine-line-studio': [
        { id: 'mock-fls-1', title: 'Ramo de flores fine line', content: 'Ramo de flores en fine line con detalles botánicos.', imageUrl: '/images/tattoos/tattoo-6.jpg', likesCount: 189, commentsCount: 34, createdAt: '2026-01-10T10:00:00Z' },
        { id: 'mock-fls-2', title: 'Silueta femenina minimalista', content: 'Silueta femenina en fine line con trazos elegantes.', imageUrl: '/images/tattoos/tattoo-10.jpg', likesCount: 245, commentsCount: 51, createdAt: '2026-02-01T10:00:00Z' },
    ],
    'real-ink-tattoo': [
        { id: 'mock-rit-1', title: 'Retrato hiperrealista', content: 'Retrato hiperrealista en escala de grises con detalles precisos.', imageUrl: '/images/tattoos/tattoo-2.jpg', likesCount: 312, commentsCount: 78, createdAt: '2025-12-15T10:00:00Z' },
        { id: 'mock-rit-2', title: 'Ave exótica a color', content: 'Ave exótica con plumaje detallado en color realista.', imageUrl: '/images/tattoos/tattoo-7.jpg', likesCount: 267, commentsCount: 54, createdAt: '2026-01-20T10:00:00Z' },
    ],
    'neo-art-studio': [
        { id: 'mock-nas-1', title: 'Neo tradicional rosa y dagas', content: 'Rosa neo tradicional con dagas cruzadas y cinta.', imageUrl: '/images/tattoos/tattoo-5.jpg', likesCount: 198, commentsCount: 41, createdAt: '2026-01-05T10:00:00Z' },
        { id: 'mock-nas-2', title: 'Neo tradicional mujer', content: 'Retrato neo tradicional de mujer con tocado floral.', imageUrl: '/images/tattoos/tattoo-4.jpg', likesCount: 156, commentsCount: 29, createdAt: '2026-02-10T10:00:00Z' },
    ],
};

export function getMockPostsForUser(userId: string): any[] {
    return MOCK_USER_POSTS[userId] || [];
}

export const MOCK_FEED_POSTS = [
    {
        id: 'mock-feed-1', title: 'Neo tradicional rosa y dagas', content: 'Neo tradicional con rosa, dagas y detalles ornamentales. Trabajo realizado en Ink Master Studio.',
        imageUrl: '/images/tattoos/tattoo-5.jpg', likesCount: 234, commentsCount: 56,
        user: { id: 'ink-master', username: 'Ink Master', avatar: '', isStudio: true },
        category: { name: 'Neo Tradicional' }, location: 'Bogotá, Colombia',
        createdAt: '2025-12-20T10:00:00Z', likedByCurrentUser: false,
    },
    {
        id: 'mock-feed-2', title: 'Lettering frase completa en espalda', content: 'Frase completa en lettering cursivo en la espalda. Caligrafía personalizada para cada cliente.',
        imageUrl: '/images/tattoos/tattoo-6.jpg', likesCount: 189, commentsCount: 42,
        user: { id: 'camilasanchez', username: 'Camila Sánchez', avatar: '' },
        category: { name: 'Lettering' }, location: 'Medellín, Colombia',
        createdAt: '2025-11-25T10:00:00Z', likedByCurrentUser: false,
    },
    {
        id: 'mock-feed-3', title: 'Color realismo ave exótica', content: 'Trabajo de realismo a color en antebrazo. Ave exótica con detalles en plumaje.',
        imageUrl: '/images/tattoos/tattoo-7.jpg', likesCount: 312, commentsCount: 78,
        user: { id: 'luis-rojas', username: 'Luis Rojas', avatar: '' },
        category: { name: 'Realismo' }, location: 'Cali, Colombia',
        createdAt: '2025-12-15T10:00:00Z', likedByCurrentUser: false,
    },
    {
        id: 'mock-feed-4', title: 'Anime sleeve completo', content: 'Manga completa de anime. Personajes y escenas detalladas en estilo japonés.',
        imageUrl: '/images/tattoos/tattoo-8.jpg', likesCount: 567, commentsCount: 102,
        user: { id: 'black-ink', username: 'Black Ink', avatar: '', isStudio: true },
        category: { name: 'Anime' }, location: 'Bogotá, Colombia',
        createdAt: '2026-01-20T10:00:00Z', likedByCurrentUser: false,
    },
    {
        id: 'mock-feed-5', title: 'Tribal brazo geométrico', content: 'Manga tribal con diseño geométrico moderno. Líneas precisas y sombreado impecable.',
        imageUrl: '/images/tattoos/tattoo-9.jpg', likesCount: 423, commentsCount: 89,
        user: { id: 'pablo-gil', username: 'Pablo Gil', avatar: '' },
        category: { name: 'Tribal' }, location: 'Bogotá, Colombia',
        createdAt: '2026-02-05T10:00:00Z', likedByCurrentUser: false,
    },
    {
        id: 'mock-feed-6', title: 'Fine line rostro femenino', content: 'Fine line de rostro femenino en antebrazo. Líneas sutiles y elegantes.',
        imageUrl: '/images/tattoos/tattoo-10.jpg', likesCount: 398, commentsCount: 67,
        user: { id: 'diana-cruz', username: 'Diana Cruz', avatar: '' },
        category: { name: 'Fine Line' }, location: 'Cali, Colombia',
        createdAt: '2026-01-10T10:00:00Z', likedByCurrentUser: false,
    },
];

export function getMockPostsForStudio(studioId: string): any[] {
    if (MOCK_STUDIO_POSTS[studioId]) return MOCK_STUDIO_POSTS[studioId];
    return [
        { id: `mock-${studioId}-1`, title: 'Trabajo destacado', content: 'Trabajo realizado en nuestro estudio.', imageUrl: '/images/tattoos/tattoo-5.jpg', likesCount: 0, commentsCount: 0, createdAt: new Date().toISOString() },
    ];
}